# Generated by Django 2.2 on 2020-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200616_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
