# Generated by Django 2.2 on 2020-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200616_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, default='none', max_length=1, null=True),
        ),
    ]
